using System.Globalization;
using System.Text;

namespace CaddyManager.Platform.Readiness;

public sealed record GpoScriptInput
{
    public string GpoName { get; init; } = GpoScriptBuilder.DefaultGpoName;
    /// <summary>DNS name of the AD domain (e.g. corp.example.com). Null when the server is not domain joined.</summary>
    public string? Domain { get; init; }
    public required string ComputerName { get; init; }
    /// <summary>Distinguished name of the computer account, when resolvable.</summary>
    public string? ComputerDn { get; init; }
    public required IReadOnlyList<RequiredFirewallRule> Rules { get; init; }
    /// <summary>True when any enabled host uses Caddy's internal CA.</summary>
    public bool InternalCaUsed { get; init; }
    /// <summary>Path of Caddy's local CA root certificate on the server.</summary>
    public string? InternalRootPath { get; init; }
    public string ProductVersion { get; init; } = "";
    public DateTime GeneratedAt { get; init; } = DateTime.UtcNow;
}

/// <summary>Builds the idempotent PowerShell script that deploys the required firewall rules through a domain GPO.</summary>
public static class GpoScriptBuilder
{
    public const string DefaultGpoName = "Caddy Proxy Manager - Firewall";

    /// <summary>Parent container of a DN: "CN=WEB01,OU=Servers,DC=corp,DC=local" → "OU=Servers,DC=corp,DC=local". Handles escaped commas.</summary>
    public static string? ParentDn(string? dn)
    {
        if (string.IsNullOrWhiteSpace(dn)) return null;
        for (var i = 0; i < dn.Length; i++)
        {
            if (dn[i] == '\\') { i++; continue; }
            if (dn[i] == ',') return dn[(i + 1)..].Trim() is { Length: > 0 } parent ? parent : null;
        }
        return null;
    }

    public static string Build(GpoScriptInput input)
    {
        static string Q(string? s) => PowerShellRunner.Quote(s);
        var ou = ParentDn(input.ComputerDn);
        var joined = !string.IsNullOrWhiteSpace(input.Domain);
        var sb = new StringBuilder();

        sb.AppendLine("<#");
        sb.AppendLine(".SYNOPSIS");
        sb.AppendLine($"    Deploys the inbound firewall rules required by Caddy Proxy Manager on {input.ComputerName} through a domain GPO.");
        sb.AppendLine();
        sb.AppendLine(".DESCRIPTION");
        sb.AppendLine($"    Generated by Caddy Proxy Manager {input.ProductVersion} on {input.GeneratedAt.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture)} UTC.");
        sb.AppendLine();
        sb.AppendLine("    Why a GPO: on domain-joined servers firewall policy is usually managed centrally, and Group Policy can");
        sb.AppendLine("    disable local rules (\"Apply local firewall rules: No\"). Rules delivered by a GPO always apply.");
        sb.AppendLine();
        sb.AppendLine("    What it does (safe to run repeatedly):");
        sb.AppendLine("      1. Creates the GPO (or reuses it when it already exists) and disables its user settings.");
        sb.AppendLine("      2. Replaces the rules below inside the GPO (New-NetFirewallRule -PolicyStore '<domain>\\<GPO>').");
        sb.AppendLine("      3. Restricts the GPO to this computer only (security filtering; -RestrictToThisComputer $false to skip).");
        sb.AppendLine("      4. Links the GPO to the OU that contains the computer account (once). Computers still in the default");
        sb.AppendLine("         CN=Computers container get the link on the domain root instead (limited to this computer by step 3).");
        sb.AppendLine();
        sb.AppendLine("    Rules:");
        foreach (var r in input.Rules)
            sb.AppendLine($"      - {r.DisplayName}: inbound {r.Protocol} {r.Port.ToString(CultureInfo.InvariantCulture)} ({r.Purpose})");
        sb.AppendLine();
        sb.AppendLine("    Requirements: run it on a domain controller or a management server / admin workstation with the Group Policy");
        sb.AppendLine("    Management Console (GroupPolicy PowerShell module) installed - member servers usually do NOT have it - as a user");
        sb.AppendLine("    allowed to create and link GPOs (e.g. Domain Admins; on a DC use an elevated prompt). Use Windows PowerShell 5.1:");
        sb.AppendLine("    in PowerShell 7 the GroupPolicy module only runs through implicit remoting and its objects cannot be modified.");
        if (!joined)
        {
            sb.AppendLine();
            sb.AppendLine("    NOTE: this server did not report an Active Directory domain. Fill in -Domain and -TargetOU before running,");
            sb.AppendLine("    or create the rules locally instead (Readiness page → Firewall → Fix).");
        }
        sb.AppendLine();
        sb.AppendLine(".EXAMPLE");
        sb.AppendLine("    .\\Deploy-CaddyProxyManagerFirewallGpo.ps1 -WhatIf");
        sb.AppendLine("    .\\Deploy-CaddyProxyManagerFirewallGpo.ps1");
        sb.AppendLine("#>");
        sb.AppendLine("#Requires -PSEdition Desktop");
        sb.AppendLine("[CmdletBinding(SupportsShouldProcess = $true)]");
        sb.AppendLine("param(");
        sb.AppendLine($"    [string] $GpoName = {Q(input.GpoName)},");
        sb.AppendLine("    # DNS name of the Active Directory domain.");
        sb.AppendLine($"    [string] $Domain = {Q(input.Domain ?? "")},");
        sb.AppendLine("    # OU (distinguished name) that contains the computer account. Empty = do not link (link manually).");
        sb.AppendLine($"    [string] $TargetOU = {Q(ou ?? "")},");
        sb.AppendLine("    # Computer the rules are meant for.");
        sb.AppendLine($"    [string] $ComputerName = {Q(input.ComputerName)},");
        sb.AppendLine("    # $true = the GPO applies only to $ComputerName (security filtering); $false = every computer in the OU.");
        sb.AppendLine("    [bool] $RestrictToThisComputer = $true");
        sb.AppendLine(")");
        sb.AppendLine();
        sb.AppendLine("Set-StrictMode -Version 2.0");
        sb.AppendLine("$ErrorActionPreference = 'Stop'");
        sb.AppendLine();
        sb.AppendLine("if ([string]::IsNullOrWhiteSpace($Domain)) { throw 'Specify -Domain (DNS name of the Active Directory domain).' }");
        sb.AppendLine("foreach ($module in 'GroupPolicy', 'NetSecurity') {");
        sb.AppendLine("    if (-not (Get-Module -ListAvailable -Name $module)) {");
        sb.AppendLine("        throw \"PowerShell module '$module' is not available. Install RSAT: Group Policy Management Tools (Install-WindowsFeature GPMC, or Add-WindowsCapability -Online -Name Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0).\"");
        sb.AppendLine("    }");
        sb.AppendLine("    Import-Module $module");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# ---------------------------------------------------------------- 1. GPO");
        sb.AppendLine("# Get-GPO reports a missing GPO as a terminating error that -ErrorAction SilentlyContinue does not suppress.");
        sb.AppendLine("$gpo = $null");
        sb.AppendLine("try { $gpo = Get-GPO -Name $GpoName -Domain $Domain -ErrorAction Stop } catch { $gpo = $null }");
        sb.AppendLine("if (-not $gpo) {");
        sb.AppendLine("    if ($PSCmdlet.ShouldProcess($GpoName, 'Create GPO')) {");
        sb.AppendLine("        $gpo = New-GPO -Name $GpoName -Domain $Domain -Comment 'Inbound firewall rules required by Caddy Proxy Manager (generated script).'");
        sb.AppendLine("        Write-Host \"Created GPO '$GpoName' ($($gpo.Id)).\"");
        sb.AppendLine("    }");
        sb.AppendLine("} else {");
        sb.AppendLine("    Write-Host \"Using existing GPO '$GpoName' ($($gpo.Id)).\"");
        sb.AppendLine("}");
        sb.AppendLine("if ($gpo -and $gpo.GpoStatus -ne 'UserSettingsDisabled' -and $PSCmdlet.ShouldProcess($GpoName, 'Disable user settings')) {");
        sb.AppendLine("    $gpo.GpoStatus = 'UserSettingsDisabled'   # only the computer half is used");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# ---------------------------------------------------------------- 2. Firewall rules inside the GPO");
        sb.AppendLine("$policyStore = \"$Domain\\$GpoName\"");
        sb.AppendLine("$rules = @(");
        for (var i = 0; i < input.Rules.Count; i++)
        {
            var r = input.Rules[i];
            sb.Append($"    @{{ DisplayName = {Q(r.DisplayName)}; Protocol = {Q(r.Protocol)}; LocalPort = {Q(r.Port.ToString(CultureInfo.InvariantCulture))}; Description = {Q(r.Description)} }}");
            sb.AppendLine(i < input.Rules.Count - 1 ? "," : "");
        }
        sb.AppendLine(")");
        sb.AppendLine("foreach ($rule in $rules) {");
        sb.AppendLine("    if (-not $PSCmdlet.ShouldProcess(\"$policyStore\", \"Create firewall rule '$($rule.DisplayName)'\")) { continue }");
        sb.AppendLine("    # Replace any previous version of the rule so the script stays idempotent.");
        sb.AppendLine("    Remove-NetFirewallRule -PolicyStore $policyStore -DisplayName $rule.DisplayName -ErrorAction SilentlyContinue");
        sb.AppendLine($"    New-NetFirewallRule -PolicyStore $policyStore -DisplayName $rule.DisplayName -Group {Q(ReadinessScripts.FirewallGroup)} `");
        sb.AppendLine("        -Description $rule.Description -Direction Inbound -Action Allow -Protocol $rule.Protocol `");
        sb.AppendLine("        -LocalPort $rule.LocalPort -Profile Any -Enabled True | Out-Null");
        sb.AppendLine("    Write-Host \"  rule: $($rule.DisplayName) ($($rule.Protocol) $($rule.LocalPort))\"");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# ---------------------------------------------------------------- 3. Security filtering (before linking, so the GPO");
        sb.AppendLine("#                                                                     never applies to the whole OU, not even briefly)");
        sb.AppendLine("if ($gpo -and $RestrictToThisComputer -and $PSCmdlet.ShouldProcess($GpoName, \"Apply only to $ComputerName\")) {");
        sb.AppendLine("    # Computer gets Read + Apply; Authenticated Users keep Read only (required since MS16-072). The group name is");
        sb.AppendLine("    # resolved from its well-known SID so the script also works on non-English domain controllers.");
        sb.AppendLine("    Set-GPPermission -Name $GpoName -Domain $Domain -TargetName $ComputerName -TargetType Computer -PermissionLevel GpoApply | Out-Null");
        sb.AppendLine("    $authUsers = (New-Object System.Security.Principal.SecurityIdentifier('S-1-5-11')).Translate([System.Security.Principal.NTAccount]).Value.Split('\\')[-1]");
        sb.AppendLine("    Set-GPPermission -Name $GpoName -Domain $Domain -TargetName $authUsers -TargetType Group -PermissionLevel GpoRead -Replace | Out-Null");
        sb.AppendLine("    Write-Host \"GPO applies only to $ComputerName.\"");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# ---------------------------------------------------------------- 4. Link to the computer's OU");
        sb.AppendLine("$linkTarget = $TargetOU");
        sb.AppendLine("if ($TargetOU -match '^CN=') {");
        sb.AppendLine("    # Computers in a container such as the default CN=Computers cannot get a linked GPO (only sites, domains and OUs can).");
        sb.AppendLine("    $domainDn = (($TargetOU -split ',') | Where-Object { $_ -match '^DC=' }) -join ','");
        sb.AppendLine("    if ($RestrictToThisComputer -and $domainDn) {");
        sb.AppendLine("        Write-Warning \"$TargetOU is a container, not an OU, so the GPO is linked to the domain root $domainDn instead; security filtering limits it to $ComputerName. Consider moving servers to an OU.\"");
        sb.AppendLine("        $linkTarget = $domainDn");
        sb.AppendLine("    } else {");
        sb.AppendLine("        Write-Warning \"$TargetOU is a container, not an OU: GPOs cannot be linked to it. Move $ComputerName to an OU and run this script with -TargetOU '<OU DN>'.\"");
        sb.AppendLine("        $linkTarget = ''");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("if ([string]::IsNullOrWhiteSpace($linkTarget)) {");
        sb.AppendLine("    Write-Warning ('The GPO was not linked ({0} is not in a known OU). Link it yourself, e.g.:' -f $ComputerName)");
        sb.AppendLine("    Write-Warning (\"  New-GPLink -Name '$GpoName' -Domain '$Domain' -Target 'OU=Servers,DC=example,DC=com' -LinkEnabled Yes\")");
        sb.AppendLine("    Write-Warning ('  Find the OU with: ([adsisearcher]\"(sAMAccountName={0}$)\").FindOne().Path' -f $ComputerName)");
        sb.AppendLine("} else {");
        sb.AppendLine("    $existingLink = (Get-GPInheritance -Target $linkTarget -Domain $Domain).GpoLinks | Where-Object { $_.DisplayName -eq $GpoName }");
        sb.AppendLine("    if ($existingLink) {");
        sb.AppendLine("        Write-Host \"GPO is already linked to $linkTarget.\"");
        sb.AppendLine("        if (-not $existingLink.Enabled -and $PSCmdlet.ShouldProcess($linkTarget, 'Enable GPO link')) {");
        sb.AppendLine("            Set-GPLink -Name $GpoName -Domain $Domain -Target $linkTarget -LinkEnabled Yes | Out-Null");
        sb.AppendLine("        }");
        sb.AppendLine("    } elseif ($PSCmdlet.ShouldProcess($linkTarget, \"Link GPO '$GpoName'\")) {");
        sb.AppendLine("        New-GPLink -Name $GpoName -Domain $Domain -Target $linkTarget -LinkEnabled Yes | Out-Null");
        sb.AppendLine("        Write-Host \"Linked GPO to $linkTarget.\"");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# ---------------------------------------------------------------- 5. Next steps");
        sb.AppendLine("Write-Host ''");
        sb.AppendLine("Write-Host \"Done. On $ComputerName run 'gpupdate /target:computer /force' (or wait for the next policy refresh), then verify:\"");
        sb.AppendLine("Write-Host \"  (remotely: Invoke-GPUpdate -Computer $ComputerName -Target Computer -RandomDelayInMinutes 0 -Force)\"");
        sb.AppendLine($"Write-Host \"  Get-NetFirewallRule -PolicyStore ActiveStore -Group {Q(ReadinessScripts.FirewallGroup)} | Format-Table DisplayName, Enabled, PolicyStoreSourceType\"");
        sb.AppendLine("Write-Host 'Then re-run the checks on the Readiness page of Caddy Proxy Manager.'");

        if (input.InternalCaUsed)
        {
            var root = input.InternalRootPath ?? @"C:\ProgramData\CaddyProxyManager\caddy\data\pki\authorities\local\root.crt";
            sb.AppendLine();
            sb.AppendLine("# ---------------------------------------------------------------- Internal CA root (hosts using Internal TLS)");
            sb.AppendLine("# Some hosts use certificates from Caddy's internal CA. Clients trust them only when Caddy's root certificate is in");
            sb.AppendLine("# their 'Trusted Root Certification Authorities' store. Download it from the Certificates page");
            sb.AppendLine($"# (GET /api/certificates/internal-root) or copy it from {root}. Deploy it with ONE of:");
            sb.AppendLine("#   a) Group Policy Management → a GPO linked to the client OUs → Computer Configuration → Policies → Windows Settings →");
            sb.AppendLine("#      Security Settings → Public Key Policies → Trusted Root Certification Authorities → Import → root.crt");
            sb.AppendLine("#   b) Publish to Active Directory so every domain member trusts it (requires Enterprise Admins):");
            sb.AppendLine("#        certutil -dspublish -f root.crt RootCA");
            sb.AppendLine("# The root is valid for 10 years; the intermediate is renewed by Caddy automatically.");
        }
        return AsciiPunctuation(sb.ToString());
    }

    /// <summary>
    /// Replaces typographic punctuation with ASCII. The script is often saved as UTF-8 without BOM and run in Windows
    /// PowerShell 5.1, which then reads it as ANSI: the UTF-8 bytes of "→" contain 0x92, which cp1252 decodes to a
    /// right single quotation mark - and PowerShell treats that as a quote, breaking single-quoted strings.
    /// (Typographic single quotes in values are already normalised by <see cref="PowerShellRunner.Quote"/>.)
    /// </summary>
    internal static string AsciiPunctuation(string s) => s
        .Replace("→", "->", StringComparison.Ordinal)
        .Replace("—", "-", StringComparison.Ordinal)
        .Replace("–", "-", StringComparison.Ordinal)
        .Replace("…", "...", StringComparison.Ordinal)
        .Replace("“", "\"", StringComparison.Ordinal)
        .Replace("”", "\"", StringComparison.Ordinal);
}
