import { useEffect, useRef, type ReactNode } from 'react';
import { Link, useLocation } from 'react-router';
import { EyeOff } from 'lucide-react';
import { useBinaryOverview } from '@/api/hooks';
import type { CaddySettings, CaddySettingsInput } from '@/api/types';
import { SecretJsonInput } from '@/components/SecretJsonInput';
import { Button, Callout, Field, FormSection, Textarea, useConfirm } from '@/components/ui';
import { jsonObjectError, type FieldErrors } from '@/lib/validation';
import {
  ACME_ISSUER_EXAMPLES,
  dnsProviderName,
  EXTRA_APPS_EXAMPLES,
  parseObject,
  RESERVED_APPS,
  TLS_POLICY_EXAMPLES,
  type JsonExample,
} from './pluginExamples';

export const PLUGIN_FIELDS = ['acmeIssuerJson', 'tlsConnectionPolicyJson', 'extraAppsJson'];

/** Client-side checks for the plugin JSON fields (the server and Caddy remain authoritative). */
export function validatePluginFields(f: CaddySettingsInput): FieldErrors {
  const e: FieldErrors = {};
  if (typeof f.acmeIssuerJson === 'string' && f.acmeIssuerJson !== '\u0000' && f.acmeIssuerJson !== '') {
    const err = jsonObjectError(f.acmeIssuerJson);
    if (err) e.acmeIssuerJson = err;
  }
  const tlsErr = jsonObjectError(f.tlsConnectionPolicyJson);
  if (tlsErr) e.tlsConnectionPolicyJson = tlsErr;
  const appsErr = jsonObjectError(f.extraAppsJson);
  if (appsErr) e.extraAppsJson = appsErr;
  else {
    const reserved = Object.keys(parseObject(f.extraAppsJson) ?? {}).filter((k) => RESERVED_APPS.includes(k));
    if (reserved.length)
      e.extraAppsJson = `${reserved.map((k) => `“${k}”`).join(', ')} ${reserved.length === 1 ? 'is' : 'are'} generated by the manager and cannot be set here. Use the host, stream and certificate pages instead.`;
  }
  return e;
}

export function HiddenValue() {
  return (
    <div className="flex h-8 items-center gap-2 rounded-md border border-border-strong bg-surface-2 px-2.5 text-sm text-fg-subtle">
      <EyeOff size={13} aria-hidden />
      Hidden — only administrators can view this value
    </div>
  );
}

function Examples({ examples, onPick, disabled }: { examples: JsonExample[]; onPick: (e: JsonExample) => void; disabled?: boolean }) {
  return (
    <div className="flex flex-wrap items-center gap-1.5 text-xs text-fg-subtle">
      <span>Examples:</span>
      {examples.map((ex) => (
        <Button key={ex.label} size="xs" variant="secondary" onClick={() => onPick(ex)} disabled={disabled} title={ex.plugin ? `Needs plugin ${ex.plugin}` : undefined}>
          {ex.label}
        </Button>
      ))}
    </div>
  );
}

/** Settings › Caddy › "Plugins & advanced": raw JSON for plugins the manager does not model directly. */
export function PluginsAdvancedSection({
  settings,
  form,
  set,
  errors,
  isAdmin: isAdminRole,
  readOnly = false,
}: {
  settings: CaddySettings;
  form: CaddySettingsInput;
  set: <K extends keyof CaddySettingsInput>(k: K, v: CaddySettingsInput[K]) => void;
  errors: FieldErrors;
  isAdmin: boolean;
  /** Managed cluster node: the values are replicated from the primary (still visible to administrators). */
  readOnly?: boolean;
}) {
  // Administrators still see the values on a node; only editing is off.
  const canView = isAdminRole;
  const isAdmin = isAdminRole && !readOnly;
  const binary = useBinaryOverview();
  const confirm = useConfirm();
  const location = useLocation();
  const anchor = useRef<HTMLSpanElement>(null);
  const modules = binary.data?.installed?.modules;

  useEffect(() => {
    if (location.hash === '#plugins-advanced') anchor.current?.scrollIntoView({ block: 'start', behavior: 'smooth' });
  }, [location.hash]);

  const fill = async (key: 'acmeIssuerJson' | 'tlsConnectionPolicyJson' | 'extraAppsJson', ex: JsonExample) => {
    const current = form[key];
    const hasText = typeof current === 'string' && current.trim() !== '' && current !== '\u0000';
    const replacingStored = key === 'acmeIssuerJson' && settings.hasAcmeIssuerJson && (current === undefined || current === null);
    if (hasText || replacingStored) {
      const ok = await confirm({
        title: `Use the “${ex.label}” example?`,
        message: replacingStored
          ? 'The stored value is replaced when you save. Fill in the placeholders first.'
          : 'The current text of this field is replaced with the example.',
        confirmLabel: 'Use example',
      });
      if (!ok) return;
    }
    set(key, ex.json);
  };

  // Plugin presence hints (only when the installed binary's module list is known).
  const issuer = parseObject(form.acmeIssuerJson);
  const provider = dnsProviderName(issuer);
  const missingProvider = provider && modules && !modules.includes(`dns.providers.${provider}`) ? provider : null;
  const apps = Object.keys(parseObject(form.extraAppsJson) ?? {}).filter((k) => !RESERVED_APPS.includes(k));
  const missingApps = modules ? apps.filter((a) => !modules.includes(a)) : [];
  const pluginsLink = (q: string, children: ReactNode) => (
    <Link to={`/caddy/plugins?q=${encodeURIComponent(q)}`} className="text-accent-text hover:underline">
      {children}
    </Link>
  );

  return (
    <FormSection
      title={
        <span id="plugins-advanced" ref={anchor} className="scroll-mt-20">
          Plugins &amp; advanced
        </span>
      }
      description={
        <>
          Configuration for Caddy plugins the manager does not model directly (Managed mode only). Install the plugin first on the{' '}
          {pluginsLink('', 'Plugins page')}. If Caddy rejects the result, the change is rolled back and the error is shown.
        </>
      }
    >
      <fieldset disabled={readOnly} className="contents">
        <Field
          label="ACME issuer options (secret JSON object)"
          error={errors.acmeIssuerJson}
          hint={
            <>
              Deep-merged into every ACME issuer after generation, for issuer options the manager does not model. Configure DNS
              providers in the ACME challenge section above instead. Stored encrypted and never shown again; secrets are masked in
              configuration views.
            </>
          }
        >
          <SecretJsonInput
            has={settings.hasAcmeIssuerJson}
            value={form.acmeIssuerJson}
            onChange={(v) => set('acmeIssuerJson', v)}
            disabled={!isAdmin}
            aria-label="ACME issuer options JSON"
            placeholder={'{\n  "challenges": {\n    "dns": { "provider": { "name": "cloudflare", "api_token": "…" } }\n  }\n}'}
          />
        </Field>
        {isAdmin && <Examples examples={ACME_ISSUER_EXAMPLES} onPick={(ex) => void fill('acmeIssuerJson', ex)} />}
        {missingProvider && (
          <Callout tone="warning" title={`DNS provider “${missingProvider}” is not installed`}>
            The installed Caddy binary has no <span className="mono">dns.providers.{missingProvider}</span> module, so Caddy will reject this
            configuration. Add <span className="mono">github.com/caddy-dns/{missingProvider}</span> on the{' '}
            {pluginsLink(`caddy-dns/${missingProvider}`, 'Plugins page')} and rebuild Caddy first.
          </Callout>
        )}

        <Field
          label="TLS connection policy (JSON object)"
          error={errors.tlsConnectionPolicyJson}
          hint="Merged into every TLS connection policy (all HTTPS sites): minimum protocol, curves, cipher suites or client-certificate authentication (mTLS)."
        >
          <Textarea
            mono
            rows={5}
            spellCheck={false}
            placeholder={'{ "protocol_min": "tls1.3" }'}
            value={form.tlsConnectionPolicyJson ?? ''}
            onChange={(e) => set('tlsConnectionPolicyJson', e.target.value)}
          />
        </Field>
        {isAdmin && <Examples examples={TLS_POLICY_EXAMPLES} onPick={(ex) => void fill('tlsConnectionPolicyJson', ex)} />}
        {!!parseObject(form.tlsConnectionPolicyJson)?.client_authentication && (
          <Callout tone="warning">
            Client-certificate authentication applies to every HTTPS site on this server, including sites used by browsers without a client
            certificate. The CA file must be readable by LocalSystem.
          </Callout>
        )}

        <Field
          label="Extra apps (JSON object)"
          error={errors.extraAppsJson}
          hint={
            <>
              Top-level Caddy apps added by plugins, keyed by app name (for example <span className="mono">dynamic_dns</span> or{' '}
              <span className="mono">crowdsec</span>). The apps the manager generates ({RESERVED_APPS.join(', ')}) cannot be overridden. This
              value is not encrypted — prefer the ACME issuer field for DNS credentials used for certificates.
            </>
          }
        >
          {canView || form.extraAppsJson !== undefined ? (
            <Textarea
              mono
              rows={6}
              spellCheck={false}
              placeholder={'{\n  "dynamic_dns": { … }\n}'}
              value={form.extraAppsJson ?? ''}
              onChange={(e) => set('extraAppsJson', e.target.value)}
            />
          ) : (
            <HiddenValue />
          )}
        </Field>
        {isAdmin && <Examples examples={EXTRA_APPS_EXAMPLES} onPick={(ex) => void fill('extraAppsJson', ex)} />}
      </fieldset>
      {missingApps.length > 0 && (
        <Callout tone="warning" title="App module not found in the installed Caddy">
          {missingApps.map((a) => (
            <span key={a} className="mono">
              {a}{' '}
            </span>
          ))}
          {missingApps.length === 1 ? 'is' : 'are'} not provided by the installed binary. Add the plugin on the{' '}
          {pluginsLink(missingApps[0], 'Plugins page')} and rebuild Caddy, or Caddy will reject the configuration.
        </Callout>
      )}
    </FormSection>
  );
}

