// Screenshots used by the documentation (docs/images, generated by mock/e2e/docs-screenshots.ts). Each has a light
// variant <name>.webp and a dark variant <name>.dark.webp; Vite emits them as hashed assets, loaded only when shown.
const files = import.meta.glob<string>('../../../docs/images/*.webp', { query: '?url', import: 'default', eager: true });

import sizes from '../../../docs/images/images.json';

const dims: Record<string, number[]> = sizes;
const urls = new Map(Object.entries(files).map(([path, url]) => [path.slice(path.lastIndexOf('/') + 1), url]));

/** Light and dark URLs for a Markdown image path such as "images/proxy-hosts-list.webp" (null when it does not exist). */
export function docImage(src: string): { light: string; dark: string; width?: number; height?: number } | null {
  const m = /^(?:\.\/)?images\/([\w-]+)\.webp$/.exec(src);
  if (!m) return null;
  const light = urls.get(`${m[1]}.webp`);
  if (!light) return null;
  const [width, height] = dims[`${m[1]}.webp`] ?? [];
  return { light, dark: urls.get(`${m[1]}.dark.webp`) ?? light, width, height };
}
