<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <RootNamespace>CaddyManager.Platform.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CaddyManager.Core\CaddyManager.Core.csproj" />
    <ProjectReference Include="..\..\src\CaddyManager.Platform\CaddyManager.Platform.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Fixtures\**\*" Exclude="Fixtures\**\._*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
